### ISSUE TITLE
Driver Error

### ISSUE THREAD

**Issue by TheNameOfAnAmatuer** [lolguy91/h0r.net#3]
Idk but this is the error

x86_64-elf-g++ -I . -fpermissive -ffreestanding -m64 -fno-use-cxa-atexit -nostdlib -fno-builtin -fno-rtti -fno-exceptions -fno-leading-underscore -c  drivers/keyboard.cpp -o drivers/keyboard.o
make: x86_64-elf-g++: Command not found
make: *** [Makefile:11: drivers/keyboard.o] Error 127

**Comment by TheNameOfAnAmatuer** [comment]
Please Resolve soon

**Comment by RevolvingMadness** [comment]
that is a error with your terminal you need to install brew
`sudo apt-get install brew`
`brew install x86_64-elf-gcc`

**Comment by lolguy91** [comment]
like rev said, this is an issue on your end
